### ISSUE TITLE
warning: "ANALOG" redefined

### ISSUE THREAD

**Issue by nandlab** [josenalde/firmata-esp32#1]
Hello,
I have replaced the ConfigurableFirmata library with your version.
I am trying to compile testesp32 for the ESP32 Dev Module, but I get this compiler warning many times for different ConfigurableFirmata *.cpp files:
```
In file included from /home/dan/Arduino/libraries/ConfigurableFirmata/src/StepperFirmata.cpp:18:
/home/dan/Arduino/libraries/ConfigurableFirmata/src/ConfigurableFirmata.h:119: warning: "ANALOG" redefined
 #define ANALOG                  0x02 // same as PIN_MODE_ANALOG
 
In file included from /home/dan/.arduino15/packages/esp32/hardware/esp32/2.0.1-RC1/cores/esp32/esp32-hal.h:79,
                 from /home/dan/.arduino15/packages/esp32/hardware/esp32/2.0.1-RC1/cores/esp32/Arduino.h:36,
                 from /home/dan/Arduino/libraries/ConfigurableFirmata/src/utility/Boards.h:22,
                 from /home/dan/Arduino/libraries/ConfigurableFirmata/src/ConfigurableFirmata.h:18,
                 from /home/dan/Arduino/libraries/ConfigurableFirmata/src/StepperFirmata.cpp:18:
/home/dan/.arduino15/packages/esp32/hardware/esp32/2.0.1-RC1/cores/esp32/esp32-hal-gpio.h:59: note: this is the location of the previous definition
 #define ANALOG            0xC0
```
Looks like the constant ANALOG is already used by the esp32 Arduino core. I tried different esp32 Arduino core versions from 1.0.0 to 2.0.1, same output. Although I can still upload the program to the board, I cannot see any pins in [firmata_test](https://github.com/firmata/firmata_test).
Is there any way to fix it?

**Comment by josenalde** [comment]
Thanks for the comment. Please verify that testesp32.ino is a clean code, without features and only one callback for sysex commands. We have included in FirmataExt.cpp a switch statement within handleSysex method. These cases refer to digital and analog IO from sysex commands. Presently, examples for python, javascript and ruby are available. Firmata_text will not respond since our FirmataExt.cpp inside ConfigurableFirmata is for sysex only.

**Comment by nandlab** [comment]
Thanks for your reply. Controlling the ESP32 worked with the python examples.
